name: AlignmentAndQCWorkflows
channels:
- bioconda
- conda-forge
- defaults
- r
dependencies:
- bedtools=2.16.2=0
- biobambam=2.0.79=0
- bwa=0.7.8=0
- fastqc=0.11.3=0
- java-jdk=8.0.92=1
- mbuffer=20160228=0
- perl-threaded=5.22.0=pl5.22.0_12
- perl-vcftools-vcf=0.797=pl5.22.0_0
- picard=1.126=4
- pysam=0.7.7=0
- r-data.table=1.10.4=r3.4.1_0
- sambamba=0.5.9=0
- samtools=0.1.19=2
- tabix=0.2.5=0
- trimmomatic=0.33=0
- vcftools=0.1.10=0
- bzip2=1.0.6=1
- cairo=1.14.6=5
- certifi=2017.11.5=py27_0
- curl=7.55.1=0
- fontconfig=2.12.1=6
- freetype=2.7=2
- gettext=0.19.7=1
- glib=2.51.4=0
- graphite2=1.3.10=0
- gsl=2.1=2
- harfbuzz=1.4.3=0
- icu=58.2=0
- jpeg=9b=2
- krb5=1.14.2=0
- libffi=3.2.1=3
- libiconv=1.15=0
- libpng=1.6.28=2
- libssh2=1.8.0=2
- libtiff=4.0.7=1
- libxml2=2.9.5=2
- ncurses=5.9=10
- nose=1.3.7=py27_2
- pango=1.40.4=0
- pcre=8.39=0
- perl=5.22.0.1=0
- pip=9.0.1=py27_0
- pixman=0.34.0=1
- r-acepack=1.4.1=r3.4.1_0
- r-backports=1.0.5=r3.4.1_0
- r-base=3.4.1=2
- r-base64enc=0.1_3=r3.4.1_0
- r-boot=1.3_18=r3.4.1_0
- r-checkmate=1.8.2=r3.4.1_0
- r-class=7.3_14=r3.4.1_0
- r-cluster=2.0.6=r3.4.1_0
- r-codetools=0.2_15=r3.4.1_0
- r-colorspace=1.3_2=r3.4.1_0
- r-dichromat=2.0_0=r3.4.1_0
- r-digest=0.6.12=r3.4.1_0
- r-evaluate=0.10.1=r3.4.1_0
- r-foreign=0.8_67=r3.4.1_0
- r-formula=1.2_1=r3.4.1_0
- r-getopt=1.20.0=r3.4.1_0
- r-ggplot2=2.2.1=r3.4.1_0
- r-gridextra=2.3=r3.4.1_0
- r-gtable=0.2.0=r3.4.1_0
- r-highr=0.6=r3.4.1_0
- r-hmisc=4.0_3=r3.4.1_0
- r-htmltable=1.9=r3.4.1_0
- r-htmltools=0.3.6=r3.4.1_0
- r-htmlwidgets=0.9=r3.4.1_0
- r-jsonlite=1.4=r3.4.1_0
- r-kernsmooth=2.23_15=r3.4.1_0
- r-knitr=1.16=r3.4.1_0
- r-labeling=0.3=r3.4.1_0
- r-lattice=0.20_34=r3.4.1_0
- r-latticeextra=0.6_28=r3.4.1_0
- r-lazyeval=0.2.0=r3.4.1_0
- r-magrittr=1.5=r3.4.1_0
- r-markdown=0.8=r3.4.1_0
- r-mass=7.3_45=r3.4.1_0
- r-matrix=1.2_7.1=r3.4.1_0
- r-mgcv=1.8_17=r3.4.1_0
- r-mime=0.5=r3.4.1_0
- r-munsell=0.4.3=r3.4.1_0
- r-nlme=3.1_131=r3.4.1_0
- r-nnet=7.3_12=r3.4.1_0
- r-plyr=1.8.4=r3.4.1_0
- r-rcolorbrewer=1.1_2=r3.4.1_0
- r-rcpp=0.12.13=r3.4.1_0
- r-reshape2=1.4.2=r3.4.1_0
- r-rlang=0.1.2=r3.4.1_0
- r-rpart=4.1_10=r3.4.1_0
- r-scales=0.4.1=r3.4.1_0
- r-spatial=7.3_11=r3.4.1_0
- r-stringi=1.1.2=r3.4.1_0
- r-stringr=1.2.0=r3.4.1_0
- r-survival=2.40_1=r3.4.1_0
- r-tibble=1.3.3=r3.4.1_0
- r-viridis=0.4.0=r3.4.1_0
- r-viridislite=0.2.0=r3.4.1_0
- r-yaml=2.1.14=r3.4.1_0
- readline=6.2=0
- setuptools=37.0.0=py27_0
- sqlite=3.19.3=1
- tk=8.5.19=2
- wheel=0.30.0=py27_2
- xz=5.2.3=0
- zlib=1.2.11=0
- libgcc=5.2.0=0
- numpy=1.7.0=py27_0
- openjdk=8.0.121=1
- openssl=1.0.1k=1
- python=2.7.9=3
- r=3.4.1=r3.4.1_0
- r-recommended=3.4.1=r3.4.1_0
- system=5.8=2
